Updated Snapcraft Desktop Helper to latest upstream version
Pass RuneLite paramaters in CLI

Update snapcraft.yaml

RuneLite CLI improvements

diff --git a/osrs/bin/sandbox-configure b/osrs/bin/sandbox-configure
--- a/osrs/bin/sandbox-configure
+++ b/osrs/bin/sandbox-configure
@@ -16,11 +16,20 @@
 #LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 #OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 #SOFTWARE.
-#################
-# Launcher init #
-#################
 
 START=$(date +%s.%N)
+
+declare -A PIDS
+function async_exec() {
+  $@ &
+  PIDS[$!]=$@
+}
+function wait_for_async_execs() {
+  for i in ${!PIDS[@]}
+  do
+    wait $i && continue || echo "ERROR: ${PIDS[$i]} exited abnormally with status $?"
+  done
+}
 
 # On Fedora $SNAP is under /var and there is some magic to map it to /snap.
 # # We need to handle that case and reset $SNAP
@@ -367,7 +376,7 @@ if [ $needs_update = true ]; then
   # included by the system fontconfig configuration: namely the
   # etc/fonts/conf.d/50-user.conf file.
   mkdir -p $XDG_CONFIG_HOME/fontconfig
-  make_user_fontconfig > $XDG_CONFIG_HOME/fontconfig/fonts.conf
+  async_exec make_user_fontconfig > $XDG_CONFIG_HOME/fontconfig/fonts.conf
 
   # the themes symlink are needed for GTK 3.18 when the prefix isn't changed
   # GTK 3.20 looks into XDG_DATA_DIR which has connected themes.
@@ -387,7 +396,7 @@ if [ $needs_update = true ]; then
   if [ ! -f $RUNTIME/usr/share/mime/mime.cache ]; then
     if command -v update-mime-database >/dev/null; then
       cp --preserve=timestamps -dR $RUNTIME/usr/share/mime $XDG_DATA_HOME
-      update-mime-database $XDG_DATA_HOME/mime
+      async_exec update-mime-database $XDG_DATA_HOME/mime
     fi
   fi
 fi
@@ -403,7 +412,7 @@ function compile_giomodules {
   fi
 }
 if [ $needs_update = true ]; then
-  compile_giomodules $RUNTIME/usr/lib/$ARCH
+  async_exec compile_giomodules $RUNTIME/usr/lib/$ARCH
 fi
 
 # Setup compiled gsettings schema
@@ -432,7 +441,7 @@ function compile_schemas {
   fi
 }
 if [ $needs_update = true ]; then
-  compile_schemas $RUNTIME/usr/lib/$ARCH/glib-2.0/glib-compile-schemas
+  async_exec compile_schemas $RUNTIME/usr/lib/$ARCH/glib-2.0/glib-compile-schemas
 fi
 
 # Enable gsettings user changes
@@ -456,7 +465,7 @@ export GDK_PIXBUF_MODULEDIR=$RUNTIME/usr/lib/$ARCH/gdk-pixbuf-2.0/2.10.0/loaders
 if [ $needs_update = true ]; then
   rm -f $GDK_PIXBUF_MODULE_FILE
   if [ -f $RUNTIME/usr/lib/$ARCH/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders ]; then
-    $RUNTIME/usr/lib/$ARCH/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > $GDK_PIXBUF_MODULE_FILE
+    async_exec $RUNTIME/usr/lib/$ARCH/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > $GDK_PIXBUF_MODULE_FILE
   fi
 fi
 
@@ -472,9 +481,9 @@ if [ $needs_update = true ]; then
           mkdir -p "$theme_dir"
           ln -s $theme/* "$theme_dir"
           if [ -f $RUNTIME/usr/sbin/update-icon-caches ]; then
-            $RUNTIME/usr/sbin/update-icon-caches "$theme_dir"
+            async_exec $RUNTIME/usr/sbin/update-icon-caches "$theme_dir"
           elif [ -f $RUNTIME/usr/sbin/update-icon-cache.gtk2 ]; then
-            $RUNTIME/usr/sbin/update-icon-cache.gtk2 "$theme_dir"
+            async_exec $RUNTIME/usr/sbin/update-icon-cache.gtk2 "$theme_dir"
           fi
         fi
       fi
@@ -500,4 +509,11 @@ mkdir -p $IBUS_CONFIG_PATH
 [ -d $IBUS_CONFIG_PATH/bus ] && rm -rf $IBUS_CONFIG_PATH/bus
 ln -sfn $REALHOME/.config/ibus/bus $IBUS_CONFIG_PATH
 
+###############################
+# Mark update and exec binary #
+###############################
+
 [ $needs_update = true ] && echo "SNAP_DESKTOP_LAST_REVISION=$SNAP_REVISION" > $SNAP_USER_DATA/.last_revision
+
+wait_for_async_execs
+
