R3 release
Used shellcheck linter and fixed suggestions

Fixed faulty conditional logic causing bad error handling.

diff --git a/rs3/bin/rs3-launcher b/rs3/bin/rs3-launcher
--- a/rs3/bin/rs3-launcher
+++ b/rs3/bin/rs3-launcher
@@ -1,5 +1,6 @@
 #!/bin/bash
-#Copyright (c) <2019> <James Carroll> All Rights Reserved
+#Copyright (c) <2019> <James Carroll>
+
 #Permission is hereby granted, free of charge, to any person obtaining a copy
 #of this software and associated documentation files (the "Software"), to deal
 #in the Software without restriction, including without limitation the rights
@@ -20,7 +21,7 @@
 
 echo "Preparing sandbox environment..."
 source sandbox-configure
-source $HOME/rs3-user-config 2>/dev/null # User can add exports/vars to this file if required, as program itself is read only.
+source "$HOME/rs3-user-config" 2>/dev/null # User can add exports/vars to this file if required, as program itself is read only.
 
 repoRoot="http://content.runescape.com/downloads/ubuntu/"
 repo="http://content.runescape.com/downloads/ubuntu/dists/trusty/"
@@ -34,70 +35,97 @@ firstRunMessage="This snap is not endorsed by Jagex. For support, check out the 
 function downloadRS3(){
 	# Does not overwrite any existing key in the event the public key is changed.
 	echo Importing Jagex Signing key
-	gpg --import $SNAP/jagex.gpg.key  
+	gpg --batch --import "$SNAP/jagex.gpg.key" 
 
 	# Clear up previous runs
 	echo Clearing previous installers
-	rm -rf $SNAP_USER_COMMON/runescape $SNAP_USER_COMMON/usr $SNAP_USER_COMMON/repoRelease $SNAP_USER_COMMON/repoRelease.gpg $SNAP_USER_COMMON/packages $SNAP_USER_COMMON/rs.deb
-	xmessage -timeout 120 $firstRunMessage &
+	rm -rf "$SNAP_USER_COMMON/runescape" "${SNAP_USER_COMMON:?}/usr" "$SNAP_USER_COMMON/repoRelease" "$SNAP_USER_COMMON/repoRelease.gpg" "$SNAP_USER_COMMON/packages" "$SNAP_USER_COMMON/rs.deb"
+	xmessage -timeout 120 "$firstRunMessage" &
 
 	echo "Downloading RuneScape repository info"
-	curl -s $repo$repoReleaseFile -o $SNAP_USER_COMMON/repoRelease
+	curl -s "$repo$repoReleaseFile" -o "$SNAP_USER_COMMON/repoRelease"
+
 	echo "Downloading RuneScape repository info signature"
-	curl -s $repo$repoReleaseSignature -o $SNAP_USER_COMMON/repoRelease.gpg
-	gpg --verify $SNAP_USER_COMMON/repoRelease.gpg $SNAP_USER_COMMON/repoRelease
-	[[ ! $? ]] && xmessage $networkError && exit 1
+	curl -s "$repo$repoReleaseSignature" -o "$SNAP_USER_COMMON/repoRelease.gpg"
+
+	if ! gpg --batch --verify "$SNAP_USER_COMMON/repoRelease.gpg" "$SNAP_USER_COMMON/repoRelease"
+	then
+		xmessage "$networkError"
+		exit 1
+	fi
 	echo "Repository info looks valid!"
-	packageFile=$(grep "SHA256" -A 10 $SNAP_USER_COMMON/repoRelease | grep amd64/Packages$ | cut -d " " -f 4)	
-	packageFileHash=$(grep "SHA256" -A 10 $SNAP_USER_COMMON/repoRelease | grep amd64/Packages$ | cut -d " " -f 2)
+
+	packageFile=$(grep "SHA256" -A 10 "$SNAP_USER_COMMON/repoRelease" | grep amd64/Packages$ | cut -d " " -f 4)	
+	packageFileHash=$(grep "SHA256" -A 10 "$SNAP_USER_COMMON/repoRelease" | grep amd64/Packages$ | cut -d " " -f 2)
 
 	echo "Downloading repository package list"
-	curl -s $repo$packageFile -o $SNAP_USER_COMMON/packages
-	[[ ! $packageFileHash == $(sha256sum $SNAP_USER_COMMON/packages | cut -d " " -f 1) ]] && xmessage $networkError && exit 1
+	curl -s "$repo$packageFile" -o "$SNAP_USER_COMMON/packages"
+
+	if [[ $packageFileHash -ne $(sha256sum "$SNAP_USER_COMMON/packages" | cut -d " " -f 1) ]]
+	then
+		xmessage "$networkError" 
+		exit 1
+	fi
 	echo "Repository package list looks valid!"
-	debFile=$(grep Filename $SNAP_USER_COMMON/packages | cut -d " " -f 2)
-	debHash=$(grep SHA256 $SNAP_USER_COMMON/packages | cut -d " " -f 2)
+
+	debFile=$(grep Filename "$SNAP_USER_COMMON/packages" | cut -d " " -f 2)
+	debHash=$(grep SHA256 "$SNAP_USER_COMMON/packages" | cut -d " " -f 2)
+
 	echo "Downloading RuneScape installer"
-	curl -s $repoRoot$debFile -o $SNAP_USER_COMMON/rs.deb
-	[[ ! $debHash == $(sha256sum $SNAP_USER_COMMON/rs.deb | cut -d " " -f 1) ]] && xmessage $networkError && exit 1
+	curl -s "$repoRoot$debFile" -o "$SNAP_USER_COMMON/rs.deb"
+
+	if [[ $debHash -ne $(sha256sum "$SNAP_USER_COMMON/rs.deb" | cut -d " " -f 1) ]]
+	then 
+		xmessage "$networkError"
+		exit 1
+	fi
 	echo "Runescape installer looks valid!"
 
 	#Extract the files and put them into the right place
-	dpkg-deb -x $SNAP_USER_COMMON/rs.deb $SNAP_USER_COMMON/
-	mv $SNAP_USER_COMMON/usr/bin/runescape-launcher $SNAP_USER_COMMON/runescape-launcher
-	chmod +x $SNAP_USER_COMMON/runescape-launcher
-	mv $SNAP_USER_COMMON/usr/share/games/runescape-launcher/runescape $SNAP_USER_COMMON/runescape
-	sed -i s?/usr/share/games/runescape-launcher/?$SNAP_USER_COMMON/?g $SNAP_USER_COMMON/runescape-launcher
+	dpkg-deb -x "$SNAP_USER_COMMON/rs.deb" "$SNAP_USER_COMMON/"
+	mv "$SNAP_USER_COMMON/usr/bin/runescape-launcher" "$SNAP_USER_COMMON/runescape-launcher"
+	chmod +x "$SNAP_USER_COMMON/runescape-launcher"
+	mv "$SNAP_USER_COMMON/usr/share/games/runescape-launcher/runescape" "$SNAP_USER_COMMON/runescape"
+	sed -i s?/usr/share/games/runescape-launcher/?"$SNAP_USER_COMMON"/?g "$SNAP_USER_COMMON/runescape-launcher"
+
 	echo "Clearing up downloads"
-	rm -rf $SNAP_USER_COMMON/usr $SNAP_USER_COMMON/repoRelease $SNAP_USER_COMMON/repoRelease.gpg $SNAP_USER_COMMON/packages $SNAP_USER_COMMON/rs.deb
+	rm -rf "${SNAP_USER_COMMON:?}/usr" "$SNAP_USER_COMMON/repoRelease" "$SNAP_USER_COMMON/repoRelease.gpg" "$SNAP_USER_COMMON/packages" "$SNAP_USER_COMMON/rs.deb"
 	
 }
 function setupDirs(){
 	echo "Directing cache to $SNAP_USER_COMMON"
 	# Set up the cache location to exist in $SNAP_USER_COMMON rather than $HOME, preventing disk waste on upgrades when $HOME is snapshot.
-	mkdir $SNAP_USER_COMMON/rs3cache/ -p
-	mkdir $SNAP_USER_DATA/Jagex/launcher/ -p
-	echo cache_folder=$SNAP_USER_COMMON/rs3cache/ > $SNAP_USER_DATA/Jagex/launcher/preferences.cfg
-	echo user_folder=$SNAP_USER_COMMON/rs3cache/ >> $SNAP_USER_DATA/Jagex/launcher/preferences.cfg
+	mkdir "$SNAP_USER_COMMON/rs3cache/" -p
+	mkdir "$SNAP_USER_DATA/Jagex/launcher/" -p
+	echo cache_folder="$SNAP_USER_COMMON"/rs3cache/ > "$SNAP_USER_DATA/Jagex/launcher/preferences.cfg"
+	echo user_folder="$SNAP_USER_COMMON"/rs3cache/ >> "$SNAP_USER_DATA/Jagex/launcher/preferences.cfg"
 }
-[[ ! -f $SNAP_USER_COMMON/runescape-launcher ]] && echo "Launcher doesn't appear to exist, running setup!" && downloadRS3 && setupDirs
+
+[[ ! -f "$SNAP_USER_COMMON/runescape-launcher" ]] && echo "Launcher doesn't appear to exist, running setup!" && downloadRS3 && setupDirs
 
 #Execute game
 echo "Launching RuneScape"
-$SNAP_USER_COMMON/runescape-launcher&
+"$SNAP_USER_COMMON"/runescape-launcher&
 
 #Hide the loading screen, since the game doesn't do this automatically.
 windowsInitially=$(xdotool search --onlyvisible --class  "RuneScape" | wc -l)
-windowsNeeded=$(( $windowsInitially + 2)) # When this many windows are open, clear all none game windows.
+windowsNeeded=$(( windowsInitially + 2)) # When this many windows are open, clear all none game windows.
 breakTime=$(( $(date +%s) + 60 )) # Used to escape infinite loop in event of unexpected client behaviour.
 
 until [[ $(xdotool search --onlyvisible --class "RuneScape" | wc -l) -eq $windowsNeeded ]]; do
 	sleep 2
-	[[ $(date +%s) -gt $breakTime ]] && echo "Error: Exiting launcher due to game loading timeout" && exit 1
+	if [[ $(date +%s) -gt $breakTime ]]
+	then
+		echo "Error: Exiting launcher due to game loading timeout"
+		exit 1
+	fi
 done
 echo "Hiding launcher window"
 sleep 2 #Prevent race condition!
-for x in $(xdotool search --class "RuneScape"); do
-        output=$(xprop -id $x)
-        [[ ! $output  == *"COMPOSITOR"*  ]] && xdotool windowunmap $x # Remove all RuneScape windows that aren't bypassing the compositor, suggesting they aren't using the GPU and hence aren't the game window.
+for XWindowID in $(xdotool search --class "RuneScape"); do
+        output=$(xprop -id "$XWindowID")
+        if [[ ! $output  == *"COMPOSITOR"*  ]]
+	then
+		xdotool windowunmap "$XWindowID" # Remove all RuneScape windows that aren't bypassing the compositor, suggesting they aren't using the GPU and hence aren't the game window.
+	fi
 done
